# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: U:/ENSC462/LAB4/github/ENSC462Lab4VideoController/source/top.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_video_controller_0_0/top_video_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_video_controller_0_0 || ORIG_REF_NAME==top_video_controller_0_0} -quiet] -quiet

# IP: bd/top/ip/top_util_vector_logic_0_0/top_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_util_vector_logic_0_0 || ORIG_REF_NAME==top_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/top/ip/top_clk_wiz_0_0/top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_clk_wiz_0_0 || ORIG_REF_NAME==top_clk_wiz_0_0} -quiet] -quiet

# XDC: u:/ENSC462/lab2b/lab4/lab4.gen/sources_1/bd/top/top_ooc.xdc
